# Generated by Django 3.1.7 on 2021-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('mode_active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
    ]
