# Generated by Django 3.1.7 on 2021-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderator', '0002_auto_20210402_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='username',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
