# Generated by Django 3.1.7 on 2021-03-26 18:56

import VIDEOSUPLOAD.VideoSizeVal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captions', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/%y', validators=[VIDEOSUPLOAD.VideoSizeVal.file_size])),
            ],
        ),
    ]
