# Generated by Django 3.1.7 on 2021-03-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='date',
        ),
    ]
