# Generated by Django 3.1.7 on 2021-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='date',
            field=models.DateField(default='2001-04-12'),
        ),
    ]
