# Generated by Django 3.1.7 on 2021-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0002_auto_20210329_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='url_64encoding',
            field=models.CharField(default='/upload/videos/', max_length=2048),
        ),
    ]
