# Generated by Django 3.1.7 on 2021-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0004_auto_20210329_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='url_64encoding',
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
