# Generated by Django 3.1.7 on 2021-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0005_auto_20210329_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='url_64encoding',
            field=models.CharField(default='/upload/videos/', max_length=2048),
        ),
    ]
