# Generated by Django 3.1.7 on 2021-03-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0006_videoupload_url_64encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='url_64encoding',
        ),
    ]
