# Generated by Django 3.1.7 on 2021-03-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0008_videoupload_url_64encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='thumbnail',
            field=models.ImageField(default='Hello.jpg', upload_to='Thumbnails/%y'),
        ),
    ]
