# Generated by Django 3.1.7 on 2021-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0009_videoupload_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
