# Generated by Django 3.1.7 on 2021-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0011_auto_20210331_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='video_link',
            field=models.CharField(max_length=2048),
        ),
    ]
