# Generated by Django 3.1.7 on 2021-04-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0012_auto_20210403_1840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('videoId', 'moderator_email')},
        ),
    ]
