# Generated by Django 3.1.7 on 2021-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0014_auto_20210403_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='Total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
