# Generated by Django 3.1.7 on 2021-04-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0015_videoupload_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
