# Generated by Django 3.1.7 on 2021-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEOSUPLOAD', '0021_videoupload_eventname'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='EventName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
